# Generated by Django 2.2.5 on 2021-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropRecommendationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fertilizer',
            fields=[
                ('fertilizer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Fertilizer ID')),
                ('fertilizer_name', models.CharField(max_length=100, unique=True, verbose_name='Fertilizer Name')),
                ('fertilizer_details', models.TextField(max_length=400, verbose_name='Fertilizer Details')),
                ('fertilizer_category', models.CharField(max_length=20, verbose_name='Fertilizer Category')),
                ('fertilizer_image', models.ImageField(upload_to='upload_images/fertilizer/', verbose_name='Fertilizer Image')),
            ],
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_image',
            field=models.ImageField(upload_to='upload_images/crop/', verbose_name='Crop Image'),
        ),
    ]
