# Generated by Django 2.2.5 on 2021-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropRecommendationApp', '0003_crop_recommed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_crop',
            field=models.CharField(max_length=100, verbose_name='Recommended Crop'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_humidity',
            field=models.FloatField(max_length=100, verbose_name='Relative Humidity'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_nitrogen',
            field=models.PositiveIntegerField(max_length=100, verbose_name='Soil Nitrogen'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_ph',
            field=models.FloatField(max_length=100, verbose_name='Soil ph'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_phosphorous',
            field=models.PositiveIntegerField(max_length=100, verbose_name='Soil Phosphorous'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_potassium',
            field=models.PositiveIntegerField(max_length=100, verbose_name='Soil Potassium'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_rainfall',
            field=models.FloatField(max_length=100, verbose_name='Rainfall'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_temperature',
            field=models.FloatField(max_length=100, verbose_name='Soil Temperature'),
        ),
    ]
