# Generated by Django 2.2.5 on 2021-06-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropRecommendationApp', '0004_auto_20210608_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_nitrogen',
            field=models.PositiveIntegerField(verbose_name='Soil Nitrogen'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_phosphorous',
            field=models.PositiveIntegerField(verbose_name='Soil Phosphorous'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_potassium',
            field=models.PositiveIntegerField(verbose_name='Soil Potassium'),
        ),
    ]
