# Generated by Django 2.2.5 on 2021-06-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CropRecommendationApp', '0005_auto_20210608_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fertilizer',
        ),
    ]
