# Generated by Django 2.2.5 on 2021-06-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crop',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Crop ID')),
                ('crop_name', models.CharField(max_length=100, unique=True, verbose_name='Crop Name')),
                ('crop_details', models.TextField(max_length=400, verbose_name='Crop Details')),
                ('crop_category', models.CharField(max_length=20, verbose_name='Crop Category')),
                ('crop_image', models.ImageField(upload_to='upload_images/', verbose_name='Crop Image')),
            ],
        ),
    ]
